/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./../components/tdesign/components/avatar/index.vue')['default']
    AvatarGroup: typeof import('./../components/tdesign/components/avatar-group/index.vue')['default']
    Badge: typeof import('./../components/tdesign/components/badge/index.vue')['default']
    Button: typeof import('./../components/tdesign/components/button/index.vue')['default']
    Cell: typeof import('./../components/tdesign/components/cell/index.vue')['default']
    CellGroup: typeof import('./../components/tdesign/components/cell-group/index.vue')['default']
    Checkbox: typeof import('./../components/tdesign/components/checkbox/index.vue')['default']
    CheckboxGroup: typeof import('./../components/tdesign/components/checkbox-group/index.vue')['default']
    Col: typeof import('./../components/tdesign/components/col/index.vue')['default']
    Divider: typeof import('./../components/tdesign/components/divider/index.vue')['default']
    Fab: typeof import('./../components/tdesign/components/fab/index.vue')['default']
    Form: typeof import('./../components/tdesign/components/form/index.vue')['default']
    FormItem: typeof import('./../components/tdesign/components/form-item/index.vue')['default']
    Icon: typeof import('./../components/tdesign/components/icon/index.vue')['default']
    Image: typeof import('./../components/tdesign/components/image/index.vue')['default']
    Input: typeof import('./../components/tdesign/components/input/index.vue')['default']
    Link: typeof import('./../components/tdesign/components/link/index.vue')['default']
    Loading: typeof import('./../components/tdesign/components/loading/index.vue')['default']
    Overlay: typeof import('./../components/tdesign/components/overlay/index.vue')['default']
    Picker: typeof import('./../components/tdesign/components/picker/index.vue')['default']
    PickerItem: typeof import('./../components/tdesign/components/picker-item/index.vue')['default']
    Popup: typeof import('./../components/tdesign/components/popup/index.vue')['default']
    Radio: typeof import('./../components/tdesign/components/radio/index.vue')['default']
    RadioGroup: typeof import('./../components/tdesign/components/radio-group/index.vue')['default']
    Rate: typeof import('./../components/tdesign/components/rate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./../components/tdesign/components/row/index.vue')['default']
    Search: typeof import('./../components/tdesign/components/search/index.vue')['default']
    Stepper: typeof import('./../components/tdesign/components/stepper/index.vue')['default']
    Switch: typeof import('./../components/tdesign/components/switch/index.vue')['default']
    TdesignUi: typeof import('./../components/tdesign/components/tdesign-ui/tdesign-ui.vue')['default']
    Textarea: typeof import('./../components/tdesign/components/textarea/index.vue')['default']
    Transition: typeof import('./../components/tdesign/components/transition/index.vue')['default']
    WeappTailwindcss: typeof import('./../components/WeappTailwindcss.vue')['default']
  }
}
